blog/users/views.py
from flask import Blueprint, render_template
from werkzeug.exceptions import NotFound
from flask_login import login_required

users = Blueprint("users", __name__, url_prefix="/users", static_folder="../static")

USERS = {
    1: {"name": "Александр", "age": 38, "nickname": "Kederly"},
    2: {"name": "Екатерина", "age": 36, "nickname": "Kate"},
}


@users.route("/")
@login_required
def user_list():
    return render_template(
        "users/list.html",
        users=USERS
    )


@users.route("/<int:pk>")
@login_required
def get_user(pk: int):
    if pk in USERS:
        user_raw = USERS[pk]
    else:
        raise NotFound("User id:{}, not found".format(pk))
    return render_template(
        "users/details.html",
        user_name=user_raw["name"]
    )


def get_user_name(pk: int):
    if pk in USERS.keys():
        return USERS[pk]

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
{% block css %}
<link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
{% endblock %}
{% include "navbar.html" %}
<body>
<div class="container">
    {% block body %}
    {% endblock %}
</div>

{% block js %}
<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
{% endblock %}
</body>
</html>

blog/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">My Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ url_for('main.main') }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.user_list') }}">Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('articles.list') }}">Articles</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('authors_app.list') }}">Authors</a>
                </li>
                {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('auth.logout') }}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('auth.login') }}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('auth.register') }}">Registration</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>