blog/forms/user.py
from flask_wtf import FlaskForm
from wtforms import StringField, validators, PasswordField, SubmitField


class UserBaseForm(FlaskForm):
    email = StringField(
        "Email Address",
        [
            validators.DataRequired(),
            validators.Email(),
            validators.Length(min=6, max=200),
        ],
        filters=[lambda data: data and data.lower()],
    )


class RegistrationForm(UserBaseForm):
    password = PasswordField(
        "Password",
        [
            validators.DataRequired(),
            validators.EqualTo("confirm", message="Passwords must match"),
        ],
    )
    confirm = PasswordField("Repeat Password")
    submit = SubmitField("Register")


class LoginForm(FlaskForm):
    email = StringField(
        "Email Address",
        [
            validators.DataRequired(),
            validators.Email(),
            validators.Length(min=6, max=200),
        ],
        filters=[lambda data: data and data.lower()],
    )
    password = PasswordField(
        "Password",
        [
            validators.DataRequired(),
        ],
    )
    submit = SubmitField("Login")

blog/users/views.py
from flask import Blueprint, render_template
from werkzeug.exceptions import NotFound
from flask_login import login_required

users = Blueprint("users", __name__, url_prefix="/users", static_folder="../static")

USERS = {
    1: {"name": "Александр", "age": 38, "nickname": "Kederly"},
    2: {"name": "Екатерина", "age": 36, "nickname": "Kate"},
}


@users.route("/")
@login_required
def user_list():
    return render_template(
        "users/list.html",
        users=USERS
    )


@users.route("/<int:pk>")
@login_required
def get_user(pk: int):
    if pk in USERS:
        user_raw = USERS[pk]
    else:
        raise NotFound("User id:{}, not found".format(pk))
    return render_template(
        "users/details.html",
        user_name=user_raw["name"]
    )


def get_user_name(pk: int):
    if pk in USERS.keys():
        return USERS[pk]

blog/templates/users/details.html
{% extends "base.html" %}



{% block body %}
<h1>
    {{ user_name }}
</h1>
{% endblock %}

blog/templates/users/list.html
{% extends "base.html" %}


{% block body %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Age</th>
            <th scope="col">Nickname</th>
        </tr>
        </thead>
        <tbody>
        {% for user_id in users %}
            <tr>
                <td>
                    <a href="{{ url_for('users.get_user', pk=user_id) }}">{{ users[user_id]["name"] }}</a>
                </td>
                <td>
                    {{ users[user_id]["age"] }}
                </td>
                <td>
                    {{ users[user_id]["nickname"] }}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}